# AI Bridge Mobile - Android APK Build Script (two-phase)

Write-Host "[build] Starting APK build..." -ForegroundColor Cyan

Set-Location $PSScriptRoot

# Phase 0: Auto-detect Android SDK
if (-not $env:ANDROID_HOME -or -not (Test-Path "$env:ANDROID_HOME\platforms")) {
    $candidates = @(
        "$env:LOCALAPPDATA\Android\Sdk",
        "$env:USERPROFILE\Android\sdk",
        "$env:APPDATA\Local\Android\Sdk"
    )
    foreach ($p in $candidates) {
        if (Test-Path "$p\platforms") {
            $env:ANDROID_HOME = $p
            break
        }
    }
}
if (-not $env:ANDROID_HOME -or -not (Test-Path "$env:ANDROID_HOME\platforms")) {
    Write-Host "  ERROR: Android SDK not found. Install Android Studio or set ANDROID_HOME." -ForegroundColor Red
    exit 1
}
Write-Host "  ANDROID_HOME = $env:ANDROID_HOME" -ForegroundColor Gray

# Detect Java
$javaCandidates = @(
    "$env:JAVA_HOME",
    "$env:LOCALAPPDATA\Programs\Java",
    "$env:USERPROFILE\java"
)
$javaFound = $false
foreach ($jc in $javaCandidates) {
    if ($jc -and (Test-Path "$jc\bin\java.exe")) {
        $env:JAVA_HOME = $jc
        $javaFound = $true
        break
    }
}
# Search deeper if not found
if (-not $javaFound) {
    $javaExe = Get-ChildItem -Path "$env:USERPROFILE" -Filter "java.exe" -Recurse -Depth 5 -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($javaExe) {
        $env:JAVA_HOME = (Split-Path (Split-Path $javaExe.FullName -Parent) -Parent)
        $javaFound = $true
    }
}
if (-not $javaFound) {
    Write-Host "  ERROR: Java not found. Install JDK 17+ and set JAVA_HOME." -ForegroundColor Red
    exit 1
}
Write-Host "  JAVA_HOME = $env:JAVA_HOME" -ForegroundColor Gray

# Set Python site-packages for serious_python
$env:SERIOUS_PYTHON_SITE_PACKAGES = (& "$PSScriptRoot\.venv\Scripts\python.exe" -c "import sysconfig; print(sysconfig.get_path('purelib'))").Trim()
Write-Host "  SITE_PACKAGES = $env:SERIOUS_PYTHON_SITE_PACKAGES" -ForegroundColor Gray

# Phase 1: Flet packaging (Python + Flutter project generation)
Write-Host ""
Write-Host "[Phase 1] Flet packaging..." -ForegroundColor Yellow
flet build apk --project "AI Bridge" --org com.aibridge --product "AI Bridge Mobile"
$fletExit = $LASTEXITCODE

# Check if Flet generated the Flutter project (it always does even if Gradle fails)
$flutterDir = "build\flutter\android"
if (-not (Test-Path "$flutterDir\settings.gradle.kts")) {
    Write-Host "  ERROR: Flutter project not generated by Flet." -ForegroundColor Red
    exit 1
}

# Phase 2: Patch and build with Gradle
Write-Host ""
Write-Host "[Phase 2] Patching mirrors and running Gradle..." -ForegroundColor Yellow

# Patch settings.gradle.kts - add Alibaba mirrors
$settingsFile = "$flutterDir\settings.gradle.kts"
$settings = Get-Content $settingsFile -Raw
if ($settings -notmatch "maven\.aliyun") {
    $settings = $settings -replace '(?<=repositories \{)\s*\n(\s*)google\(\)', "`n`$1maven { url = uri(`"https://maven.aliyun.com/repository/google`") }`n`$1maven { url = uri(`"https://maven.aliyun.com/repository/public`") }`n`$1maven { url = uri(`"https://maven.aliyun.com/repository/gradle-plugin`") }`n`$1google()"
    Set-Content $settingsFile $settings -NoNewline
    Write-Host "  Patched settings.gradle.kts" -ForegroundColor Green
}

# Patch build.gradle.kts - add Alibaba mirrors
$buildFile = "$flutterDir\build.gradle.kts"
$build = Get-Content $buildFile -Raw
if ($build -notmatch "maven\.aliyun") {
    $build = $build -replace '(?<=repositories \{)\s*\n(\s*)google\(\)', "`n`$1maven { url = uri(`"https://maven.aliyun.com/repository/google`") }`n`$1maven { url = uri(`"https://maven.aliyun.com/repository/public`") }`n`$1google()"
    Set-Content $buildFile $build -NoNewline
    Write-Host "  Patched build.gradle.kts" -ForegroundColor Green
}

# Patch gradle-wrapper.properties - use Tencent mirror
$wrapperFile = "$flutterDir\gradle\wrapper\gradle-wrapper.properties"
$wrapper = Get-Content $wrapperFile -Raw
if ($wrapper -match "services\.gradle\.org") {
    $wrapper = $wrapper -replace 'https\\://services\.gradle\.org', 'https\://mirrors.cloud.tencent.com/gradle'
    Set-Content $wrapperFile $wrapper -NoNewline
    Write-Host "  Patched gradle-wrapper.properties" -ForegroundColor Green
}

# Run Gradle directly
Write-Host "  Running Gradle assembleDebug..." -ForegroundColor Yellow
$env:PATH = "$env:JAVA_HOME\bin;$env:ANDROID_HOME\platform-tools;$env:PATH"

Push-Location $flutterDir
& .\gradlew.bat assembleDebug --no-daemon
$gradleExit = $LASTEXITCODE
Pop-Location

if ($gradleExit -ne 0) {
    Write-Host ""
    Write-Host "[build] FAILED. Check Gradle output above." -ForegroundColor Red
    exit 1
}

# Copy APK to build/apk/
$apkSrc = "build\flutter\build\app\outputs\flutter-apk\app-debug.apk"
New-Item -ItemType Directory -Force -Path "build\apk" | Out-Null
Copy-Item $apkSrc "build\apk\AI-Bridge-Mobile.apk" -Force

Write-Host ""
Write-Host "[build] Done! APK: build\apk\AI-Bridge-Mobile.apk" -ForegroundColor Green
